version: '3'

services:
  momoka-lite:
    build: ../
    command: --origins "*" --dir "/go/bin/pb_data" --http "0.0.0.0:8090"
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - pb_data:/go/bin/pb_data

volumes:
  pb_data:
